/**
 * The tracker contract, implemented in TypeScript for the host that cannot
 * run tk (SPEC §3.1, line 191; `contracts/tk-json-manifest.json` `hosts`).
 *
 * A Cloudflare Workflow or isolate cannot execute a Go binary, so on this
 * host the reconciler cannot shell out to tk. `tk --json` defines the tracker
 * contract; this module is its consumer implementation on that host: the
 * reads and controlled writes the manifest publishes, performed against
 * `.tick/` records through the contents API — and NOTHING ELSE. It is a
 * consumer of the contract, not a second tracker: every host that can run tk
 * runs tk, and this module exists only because its host cannot.
 *
 * Two things keep this implementation honest rather than merely present:
 *
 * 1. **The pinned fixtures certify it, not inspection.** `tracker-client.test.ts`
 *    validates every read's output against the manifest's own schemas, pins
 *    the behavioural rules the manifest's command descriptions state (null
 *    versus [], the ready ordering, the claim's idempotence, the note's
 *    provenance boundary, the close's refusals), and drives the encoder
 *    through `contracts/tracker-layout.json`. A fixture break fails this
 *    build. The module was written from the manifest and the behaviours the
 *    fixtures describe, not by eyeballing tk's output.
 *
 * 2. **The writes are tk's writes.** Each controlled write commits exactly
 *    the record `tk update`/`tk note`/`tk close`/`tk reopen` would commit —
 *    same field order (Go's `tick.Tick` struct), same `omitempty` rules, same
 *    string escaping (Go's encoding/json escapes `<`, `>`, `&` and the line
 *    separators; JSON.stringify does not), same idempotence (a re-claim
 *    keeps its `started_at`), same refusals (a tick with an unmet `--requires`
 *    gate is routed to `awaiting`, never closed) — because the two writers
 *    write the same files in the same repository, and a divergence is a
 *    record the other writer refuses. The proof is not this paragraph: the
 *    pinned tk corpus (cloudflare/test/fixtures/tk-write-corpus.json,
 *    generated by internal/tkcorpus from a real tk binary) byte-compares the
 *    client's committed records against tk's own for a generated corpus of
 *    writes, so neither side can drift quietly.
 *
 * What this module deliberately does NOT implement, and why:
 *
 *  - `tk version`: a property of a binary, and there is no binary here. The
 *    manifest's `version` entry is how a consumer checks the binary it is
 *    about to call; a host that does not call the binary has nothing to
 *    report. `manifestContract` below is the answer this host CAN give: which
 *    contract version its implementation targets.
 *  - `tk status` as a working-tree answer: this host reads `.tick/` at a
 *    commit, and a commit is always clean. `status()` reports that honestly
 *    (`changes: null`) rather than pretending to a porcelain it has no tree
 *    for. No caller of this client has a working tree to compare against.
 *  - `merge-file` / `merge-activity`: git custom merge DRIVERS, invoked by
 *    git with worktree paths. A Workflow has no worktree; the run branch is
 *    published, not merged locally.
 */

import { type ContentsStore, contentsStore, type StoredFile } from "./git-contents";
import { declaredMaxParallel, RUNNERS_CONFIG_PATH } from "./repo-config";
import { TICK_RECORD_DIR } from "./tick-membership";

/**
 * The pinned manifest's own numbers, mirrored here because src/ cannot import
 * outside cloudflare (test/isolation.test.ts). They stay honest the same
 * way Go's `internal/tk` keeps its constants honest: the certification tests
 * assert these equal the pinned bundle, so a fixture bump that does not pass
 * through this file fails the build instead of silently describing a contract
 * this client no longer serves.
 */
export const MANIFEST_CONTRACT = 1;

export const MANIFEST_MIN_TK_VERSION = "0.32.0";

import type { Env } from "./index";

// ------------------------------------------------------------ the record ---

/**
 * One tick record, the fields `#/$defs/tick` in the pinned manifest defines.
 *
 * Optional fields are omitted rather than emitted as null, and a consumer
 * must treat absence as the empty value — so this type's optionals are the
 * record's own emptiness, not a TS convenience: `encodeTick` writes a record
 * Go's `Store.Write` accepts unchanged, byte for byte.
 */
export type Tick = {
  id: string;
  title: string;
  description?: string;
  notes?: string;
  status: string;
  priority: number;
  type: string;
  owner: string;
  labels?: string[];
  blocked_by?: string[];
  after?: string[];
  parent?: string;
  target_date?: string;
  role?: string;
  discovered_from?: string;
  acceptance_criteria?: string;
  defer_until?: string;
  external_ref?: string;
  trace_id?: string;
  manual?: boolean;
  base_branch?: string;
  requires?: string;
  awaiting?: string;
  /** `approved` or `rejected`; absent when nobody has decided. */
  verdict?: string;
  created_by: string;
  created_at: string;
  updated_at: string;
  started_at?: string;
  closed_at?: string;
  closed_reason?: string;
};

/** Go's `tick.Tick` field order — part of the contract, not cosmetics. */
const TICK_FIELD_ORDER: string[] = [
  "id",
  "title",
  "description",
  "notes",
  "status",
  "priority",
  "type",
  "owner",
  "labels",
  "blocked_by",
  "after",
  "parent",
  "target_date",
  "role",
  "discovered_from",
  "acceptance_criteria",
  "defer_until",
  "external_ref",
  "trace_id",
  "manual",
  "base_branch",
  "requires",
  "awaiting",
  "verdict",
  "created_by",
  "created_at",
  "updated_at",
  "started_at",
  "closed_at",
  "closed_reason",
];

/** The fields Go's struct never omits, whatever their value. */
const ALWAYS_PRESENT = new Set(["created_by", "created_at", "updated_at"]);

function isEmpty(value: unknown): boolean {
  if (value === undefined || value === null) return true;
  if (typeof value === "string") return value === "";
  if (Array.isArray(value)) return value.length === 0;
  if (typeof value === "boolean") return value === false;
  return false;
}

/**
 * Go's string escaping, applied to what JSON.stringify produced.
 *
 * Go's encoding/json — which is what tk writes records with — escapes more
 * than JSON.stringify does, even inside strings: `<`, `>`, `&` (its default
 * HTML escaping) and the two line separators U+2028/U+2029. Those are byte
 * differences between two writers of the same file (tick v3q): a record
 * this client writes must be the record tk would write, because the two
 * write the same files in the same repository and a divergence is a diff
 * nobody can review.
 *
 * Everything JSON.stringify emits for a string already matches current Go:
 * `\"`, `\\`, the `\n \r \t \b \f` short escapes, lowercase `\u00xx` for
 * the other control bytes, and raw UTF-8 for everything else. This pass
 * walks the serialized text and rewrites only inside string tokens, so
 * structural JSON (field names, braces, the numbers) is untouched.
 */
function goEscape(text: string): string {
  let out = "";
  let inString = false;
  for (let i = 0; i < text.length; i += 1) {
    const c = text.charAt(i);
    if (!inString) {
      if (c === '"') inString = true;
      out += c;
      continue;
    }
    if (c === '"') {
      inString = false;
      out += c;
      continue;
    }
    // Keep JSON.stringify's own escapes — they are Go's own for every byte
    // either of them escapes short (`\n`, `\t`, `\b`, `\f`, `\"`, `\\`,
    // `\u00xx`).
    if (c === "\\") {
      out += c;
      out += text.charAt(i + 1);
      i += 1;
      continue;
    }
    if (c === "<") {
      out += "\\u003c";
    } else if (c === ">") {
      out += "\\u003e";
    } else if (c === "&") {
      out += "\\u0026";
    } else if (c === "\u2028") {
      out += "\\u2028";
    } else if (c === "\u2029") {
      out += "\\u2029";
    } else {
      out += c;
    }
  }
  return out;
}

/**
 * Encodes one tick record the way Go's `Store.Write` does: `tick.Tick`'s
 * field order, `omitempty` on exactly the fields that carry it, two-space
 * indent, no trailing newline — and Go's own string escaping (see
 * `goEscape`), byte for byte what `json.MarshalIndent` writes.
 *
 * Field ORDER is part of the contract: this module and `tk` write the same
 * file in the same repository, and a diff that is real content one way and
 * field reordering the other is a diff nobody can review.
 * `tracker-layout.json`'s `written_by_the_control_plane` pins the indent and
 * the required-field set this encoder must not drift from; the pinned tk
 * corpus (cloudflare/test/fixtures/tk-write-corpus.json) byte-compares this
 * encoder's output against a real tk's.
 */
export function encodeTick(tick: Tick): string {
  const record: Record<string, unknown> = {};
  for (const field of TICK_FIELD_ORDER) {
    const value = (tick as Record<string, unknown>)[field];
    if (!ALWAYS_PRESENT.has(field) && isEmpty(value)) continue;
    record[field] = value;
  }
  return goEscape(JSON.stringify(record, null, 2));
}

/** The fields a record must carry for this client to read it (`#/$defs/tick`). */
export const TICK_REQUIRED_FIELDS = [
  "id",
  "title",
  "status",
  "priority",
  "type",
  "owner",
  "created_by",
  "created_at",
  "updated_at",
] as const;

/**
 * Parses one tick record. null (not a throw) when the text is not a record
 * `tk` would read: a file this host cannot parse is an answer — unreadable —
 * the same way `tick-membership.ts` treats it, never a crash.
 */
export function parseTick(text: string): Tick | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    return null;
  }
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) return null;
  const record = parsed as Record<string, unknown>;
  for (const field of TICK_REQUIRED_FIELDS) {
    if (record[field] === undefined) return null;
  }
  if (typeof record.id !== "string" || typeof record.status !== "string") return null;
  if (typeof record.priority !== "number" || !Number.isSafeInteger(record.priority)) return null;
  return parsed as Tick;
}

// ------------------------------------------------------------- the reads ---

/** The envelope `tk list` and `tk ready` share (`#/$defs/tick_list`). */
export type TickList = {
  /** null, not [], when nothing matches — a Go nil slice marshals to null. */
  ticks: Tick[] | null;
};

/** `tk next --json`: the tick plus the action annotation. */
export type NextTick = Tick & {
  action: "implement" | "plan" | "await";
};

/** `tk deps --json`. */
export type Dependencies = {
  /** The tick's own `blocked_by`, as stored. null, not [], when empty. */
  blocked_by: string[] | null;
  /** Full tick records that name this tick in their `blocked_by`. */
  blocks: Tick[] | null;
};

/** `tk graph --json`: one wave, `#/$defs/graph_task` items. */
export type GraphTask = {
  id: string;
  title: string;
  description?: string;
  acceptance_criteria?: string;
  priority: number;
  type?: string;
  labels?: string[] | null;
  status: string;
  role?: string;
  blocked_by?: string[];
  blocks?: string[];
  awaiting?: string;
  deferred_until?: string;
  agent_ready: boolean;
};

export type GraphWave = {
  wave: number;
  parallel: number;
  ready: boolean;
  tasks: GraphTask[] | null;
};

export type Graph = {
  epic: { id: string; title: string };
  needs_planning: boolean;
  missing_process_ticks: string[] | null;
  unjustified_gates: string[] | null;
  stats: {
    total_tasks: number;
    wave_count: number;
    max_parallel: number;
    ready_for_agent: number;
    awaiting_human: number;
    deferred: number;
  };
  dispatch: {
    max_parallel: number;
    source?: string;
    in_flight: number;
    in_flight_ids: string[] | null;
    free: number;
    now: string[] | null;
  };
  waves: GraphWave[] | null;
  critical_path: number;
};

// ------------------------------------------------------------ the writes ---

/**
 * What one controlled write did. The manifest publishes each write as a
 * command that returns the record it wrote — so a consumer never has to
 * follow a write with a read — or refuses. A refusal is an answer, not an
 * error, and `reason` is the machine-checkable part (`wave_full` is a
 * retry-when-a-slot-frees, `gate` routes a close to a human).
 */
export type TrackerWrite =
  | { state: "written"; tick: Tick }
  | { state: "refused"; reason: "wave_full" | "gate" | "not_found"; detail: string; tick?: Tick };

/**
 * How many times a write that hit a ref conflict is retried. The conflict is
 * the tracker branch moving under the read — another writer, almost always
 * the run itself publishing records — and the retry lands on top of
 * whatever landed, the same shape `tracker-write.ts` uses for its creates.
 */
export const MAX_WRITE_ATTEMPTS = 6;

// ------------------------------------------------------------ the client ---

export type TrackerClientOptions = {
  /** Injected so tests are deterministic; defaults to real time. */
  now?: () => Date;
  /**
   * `[orchestration].max_parallel` when the caller has already read it (the
   * reconciler reads the run branch's declaration once per pass). When
   * absent, `graph` and `claim` read it from the store the same way tk does.
   */
  maxParallel?: number;
  maxParallelSource?: string;
};

function isAwaitingHuman(tick: Tick): boolean {
  return typeof tick.awaiting === "string" && tick.awaiting !== "";
}

function isDeferred(tick: Tick, now: Date): boolean {
  return typeof tick.defer_until === "string" && Date.parse(tick.defer_until) > now.getTime();
}

/** `query.SortByPriorityCreatedAt`: in_progress first, then priority, creation, id. */
function readyOrder(a: Tick, b: Tick): number {
  const aInProgress = a.status === "in_progress";
  const bInProgress = b.status === "in_progress";
  if (aInProgress !== bInProgress) return aInProgress ? -1 : 1;
  if (a.priority !== b.priority) return a.priority - b.priority;
  const aAt = Date.parse(a.created_at);
  const bAt = Date.parse(b.created_at);
  if (aAt !== bAt) return aAt - bAt;
  return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
}

/** RFC3339 the way Go's time.Time marshals: UTC, ISO. */
function rfc3339(now: Date): string {
  return now.toISOString();
}

/** tk's note line timestamp: minute precision, no seconds, no zone. */
function noteTimestamp(now: Date): string {
  const pad = (n: number) => String(n).padStart(2, "0");
  return (
    `${now.getUTCFullYear()}-${pad(now.getUTCMonth() + 1)}-${pad(now.getUTCDate())} ` +
    `${pad(now.getUTCHours())}:${pad(now.getUTCMinutes())}`
  );
}

function appendNote(notes: string | undefined, line: string): string {
  return (notes ?? "").trim() === "" ? line : `${(notes as string).replace(/\s+$/, "")}\n${line}`;
}

/**
 * The tracker contract client.
 *
 * One instance serves one (project, ref): the ref is the RUN BRANCH, the
 * branch this EpicRun both reads its tracker from and writes its tracker
 * records to — a tick record this Workflow commits anywhere else is one the
 * run's own workers cannot read.
 */
export class TrackerClient {
  readonly store: ContentsStore;
  readonly project: string;
  readonly ref: string;
  #now: () => Date;
  #declaredWidth: { value: number; source: string } | null;

  constructor(
    store: ContentsStore,
    project: string,
    ref: string,
    options: TrackerClientOptions = {},
  ) {
    this.store = store;
    this.project = project;
    this.ref = ref;
    this.#now = options.now ?? (() => new Date());
    this.#declaredWidth =
      options.maxParallel !== undefined
        ? { value: options.maxParallel, source: options.maxParallelSource ?? "" }
        : null;
  }

  /** The one answer this host can give about `tk version`: the contract it serves. */
  manifestContract(): { contract: number; min_tk_version: string } {
    return { contract: MANIFEST_CONTRACT, min_tk_version: MANIFEST_MIN_TK_VERSION };
  }

  /** `tk status --json` for a host with no working tree: a commit is always clean. */
  status(): { changes: null } {
    return { changes: null };
  }

  /**
   * Reads every tick record on the ref, parsed, in id order.
   *
   * Through the host's bulk read when it has one (tick 8xd). Per-file reads
   * do not survive a real tracker: ~1100 records is ~1100 requests, and
   * GitHub's secondary limit is 900 POINTS PER MINUTE for REST where most
   * GETs cost a point — so the cost is the same however the requests are
   * paced. Serial it was a fourteen-minute pass that outlived its own
   * three-minute publish slot; concurrent it was 403s. The GitHub store
   * answers this from one repository archive instead.
   *
   * A store with no bulk answer — a test's in-memory fake — falls back to
   * list-and-read, where a per-path read costs nothing.
   */
  async #all(): Promise<Tick[]> {
    const paths = (await this.store.list(`${TICK_RECORD_DIR}`)).filter((p) => p.endsWith(".json"));
    const contents = await this.#contentsOf(paths);
    const ticks: Tick[] = [];
    for (const content of contents) {
      if (content === null) continue;
      const tick = parseTick(content);
      if (tick === null) continue;
      ticks.push(tick);
    }
    ticks.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
    return ticks;
  }

  /** The bodies of `paths`, in the order asked, however this host serves them. */
  async #contentsOf(paths: string[]): Promise<(string | null)[]> {
    if (this.store.readAll !== undefined) {
      const bulk = await this.store.readAll(TICK_RECORD_DIR);
      return paths.map((path) => bulk.get(path) ?? null);
    }
    const out: (string | null)[] = [];
    for (const path of paths) {
      const file = await this.store.read(path);
      out.push(file === null ? null : file.content);
    }
    return out;
  }

  async #find(id: string): Promise<{ tick: Tick; file: StoredFile } | null> {
    const file = await this.store.read(`${TICK_RECORD_DIR}/${id}.json`);
    if (file === null) return null;
    const tick = parseTick(file.content);
    if (tick === null) return null;
    return { tick, file };
  }

  async show(id: string): Promise<Tick | null> {
    const found = await this.#find(id);
    return found === null ? null : found.tick;
  }

  async list(): Promise<TickList> {
    const ticks = await this.#all();
    return { ticks: ticks.length === 0 ? null : ticks };
  }

  /** `tk ready --all`: open or in_progress, blockers closed, not deferred, not gated. */
  async ready(): Promise<TickList> {
    const ticks = await this.#all();
    const index = new Map(ticks.map((t) => [t.id, t] as const));
    const now = this.#now();
    const pool = ticks.filter((t) => {
      if (t.status !== "open" && t.status !== "in_progress") return false;
      if (isDeferred(t, now)) return false;
      if (isAwaitingHuman(t)) return false;
      for (const blocker of t.blocked_by ?? []) {
        const found = index.get(blocker);
        // A missing blocker is treated as closed — orphaned references stay ready.
        if (found !== undefined && found.status !== "closed") return false;
      }
      return true;
    });
    pool.sort(readyOrder);
    return { ticks: pool.length === 0 ? null : pool };
  }

  /** `tk next --all`: the one next thing to work on, with its action. */
  async next(): Promise<NextTick | null> {
    const ready = await this.ready();
    if (ready.ticks !== null && ready.ticks.length > 0) {
      const tick = ready.ticks[0];
      // The action describes WHAT TO DO with the tick: a childless, open,
      // unblocked epic that wins the pool still needs planning — the rule
      // `nextAction` applies to whatever the selection produced.
      const all = await this.#all();
      const planningEpic = tick.type === "epic" && !all.some((child) => child.parent === tick.id);
      return { ...tick, action: planningEpic ? "plan" : "implement" };
    }
    const ticks = await this.#all();
    const now = this.#now();
    // `plan`: an open, unblocked, undeferred, ungated, CHILDLESS epic — the
    // epics `query.EpicsNeedingPlanning` answers with. Everything else has
    // no next action for an agent on this surface.
    const epics = ticks.filter(
      (t) =>
        t.type === "epic" &&
        t.status === "open" &&
        !isDeferred(t, now) &&
        !isAwaitingHuman(t) &&
        (t.blocked_by ?? []).every((b) => {
          const found = ticks.find((other) => other.id === b);
          return found === undefined || found.status === "closed";
        }) &&
        !ticks.some((child) => child.parent === t.id),
    );
    epics.sort(readyOrder);
    if (epics.length > 0) return { ...epics[0], action: "plan" };
    return null;
  }

  /** `tk deps <id> --json`: the edges touching one tick, null (not []) when empty. */
  async deps(id: string): Promise<Dependencies | null> {
    const found = await this.#find(id);
    if (found === null) return null;
    const tick = found.tick;
    const all = await this.#all();
    const blocks = all.filter((other) => (other.blocked_by ?? []).includes(id));
    return {
      blocked_by: tick.blocked_by && tick.blocked_by.length > 0 ? tick.blocked_by : null,
      blocks: blocks.length > 0 ? blocks : null,
    };
  }

  /**
   * `[orchestration].max_parallel` as tk reads it: from the run branch's own
   * `.tick/runners.toml`. Unreadable or absent is 0 — "no configured width" —
   * carried, never thrown: this read is advisory in `graph`, and the CLAIM is
   * where the width is enforced.
   */
  async #width(): Promise<{ value: number; source: string }> {
    if (this.#declaredWidth !== null) return this.#declaredWidth;
    try {
      const config = await this.store.read(RUNNERS_CONFIG_PATH);
      if (config === null) return { value: 0, source: "" };
      const declared = declaredMaxParallel(config.content);
      return declared === null
        ? { value: 0, source: "" }
        : { value: declared, source: RUNNERS_CONFIG_PATH };
    } catch {
      return { value: 0, source: "" };
    }
  }

  /**
   * `tk graph <epic-id> --json`: the epic's wave plan and its dispatch-now
   * answer. `dispatch.now` — never `stats.max_parallel` — is how many
   * implementers may be launched right now; the manifest's own description
   * pins that conflating the two over-dispatches a wave.
   */
  async graph(epicId: string): Promise<Graph | null> {
    const epicFile = await this.store.read(`${TICK_RECORD_DIR}/${epicId}.json`);
    if (epicFile === null) return null;
    const epic = parseTick(epicFile.content);
    if (epic === null || epic.type !== "epic") return null;

    const all = await this.#all();
    const byID = new Map(all.map((t) => [t.id, t] as const));
    const now = this.#now();

    // Non-epic children; closed ones are not part of the plan (tk --all is
    // not this surface).
    const tasks = all.filter(
      (t) => t.parent === epicId && t.type !== "epic" && t.status !== "closed",
    );

    if (tasks.length === 0) {
      // A childless epic's signal is needs_planning; planning creates the
      // skeleton, so the process-tick lint only speaks once children exist.
      // The zero-valued fields are Go's zero values: a struct field marshals
      // as its zero, a nil slice as null.
      const needsPlanning =
        epic.status === "open" &&
        !isDeferred(epic, now) &&
        !isAwaitingHuman(epic) &&
        (epic.blocked_by ?? []).every((b) => {
          const found = byID.get(b);
          return found === undefined || found.status === "closed";
        });
      return {
        epic: { id: epic.id, title: epic.title },
        needs_planning: needsPlanning,
        missing_process_ticks: [],
        unjustified_gates: [],
        stats: {
          total_tasks: 0,
          wave_count: 0,
          max_parallel: 0,
          ready_for_agent: 0,
          awaiting_human: 0,
          deferred: 0,
        },
        dispatch: { max_parallel: 0, in_flight: 0, in_flight_ids: null, free: 0, now: null },
        waves: null,
        critical_path: 0,
      };
    }

    // Wave computation. Eligible: not closed (already excluded), not gated
    // by a human. BlockedBy between eligible children delays normally; an
    // open blocker OUTSIDE the eligible set — cross-epic, or a sibling gated
    // by a human — is a virtual wave-1 node: it holds its dependents back
    // without ever being emitted. The same shape `internal/wave/wave.go`
    // implements, re-expressed here because the host cannot import it and
    // the fixtures must not let it drift.
    const eligible = tasks.filter((t) => !isAwaitingHuman(t));
    const eligibleIDs = new Set(eligible.map((t) => t.id));

    const waveInDegree = new Map<string, number>();
    const dependents: Map<string, string[]> = new Map();
    // The DISPLAY view: every open blocker of a child, wherever it lives.
    // agent_ready, stats and dispatch.now read THIS map, the way graph.go's
    // own inDegree does.
    const openBlockers: Map<string, string[]> = new Map();
    const virtual = new Set<string>();
    for (const t of eligible) waveInDegree.set(t.id, 0);
    for (const t of tasks) {
      for (const blockerID of t.blocked_by ?? []) {
        const blocker = byID.get(blockerID);
        if (blocker === undefined || blocker.status === "closed") continue;
        openBlockers.set(t.id, [...(openBlockers.get(t.id) ?? []), blockerID]);
        dependents.set(blockerID, [...(dependents.get(blockerID) ?? []), t.id]);
      }
    }
    for (const t of eligible) {
      for (const blockerID of t.blocked_by ?? []) {
        if (eligibleIDs.has(blockerID)) {
          waveInDegree.set(t.id, (waveInDegree.get(t.id) ?? 0) + 1);
        } else if (byID.has(blockerID) && byID.get(blockerID)!.status !== "closed") {
          virtual.add(blockerID);
          waveInDegree.set(t.id, (waveInDegree.get(t.id) ?? 0) + 1);
        }
      }
    }

    const remaining = new Set(eligible.map((t) => t.id));
    const remainingVirtual = new Set(virtual);
    const waves: Array<{ level: number; tasks: Tick[] }> = [];
    let waveNum = 1;
    while (remaining.size > 0) {
      const readyTasks = eligible
        .filter((t) => remaining.has(t.id) && (waveInDegree.get(t.id) ?? 0) === 0)
        .sort((a, b) =>
          a.priority !== b.priority ? a.priority - b.priority : a.id < b.id ? -1 : 1,
        );
      if (readyTasks.length === 0 && remainingVirtual.size === 0) {
        // Cycle: the waves computed so far stand, the rest is reported by
        // being absent, the same stop tk's loop takes.
        break;
      }
      if (readyTasks.length > 0) waves.push({ level: waveNum, tasks: [...readyTasks] });
      for (const t of readyTasks) {
        remaining.delete(t.id);
        for (const depID of dependents.get(t.id) ?? []) {
          if (remaining.has(depID)) waveInDegree.set(depID, (waveInDegree.get(depID) ?? 0) - 1);
        }
      }
      for (const id of [...remainingVirtual]) {
        remainingVirtual.delete(id);
        for (const depID of dependents.get(id) ?? []) {
          if (remaining.has(depID)) waveInDegree.set(depID, (waveInDegree.get(depID) ?? 0) - 1);
        }
      }
      waveNum += 1;
    }

    // Stats over the whole child set, against the DISPLAY map.
    let readyForAgent = 0;
    let awaitingHuman = 0;
    let deferred = 0;
    for (const t of tasks) {
      if (isDeferred(t, now)) deferred += 1;
      else if (isAwaitingHuman(t)) awaitingHuman += 1;
      else if ((openBlockers.get(t.id)?.length ?? 0) === 0) readyForAgent += 1;
    }

    const maxParallel = waves.reduce((max, w) => Math.max(max, w.tasks.length), 0);

    // The dispatch-now answer, from the same width the claim gate enforces.
    const width = await this.#width();
    const inFlightIDs = all
      .filter((t) => t.parent === epicId && t.type !== "epic" && t.status === "in_progress")
      .map((t) => t.id)
      .sort();
    let free = -1;
    if (width.value > 0) free = Math.max(0, width.value - inFlightIDs.length);
    const nowIDs: string[] = [];
    for (const w of waves) {
      if (w.level !== 1) continue;
      for (const t of w.tasks) {
        if (free >= 0 && nowIDs.length >= free) break;
        if (isDeferred(t, now) || isAwaitingHuman(t)) continue;
        if ((openBlockers.get(t.id)?.length ?? 0) > 0) continue;
        if (t.status === "closed" || t.status === "in_progress") continue;
        nowIDs.push(t.id);
      }
    }

    // The EPIC-SKELETON lint, in canonical order: review before closeout.
    // Children of ANY status satisfy the skeleton.
    const rolesPresent = new Set(
      all
        .filter(
          (t) => t.parent === epicId && typeof t.role === "string" && (t.role as string) !== "",
        )
        .map((t) => t.role as string),
    );
    const missingProcess: string[] = [];
    for (const role of ["review", "closeout"]) {
      if (!rolesPresent.has(role)) missingProcess.push(role);
    }

    // Planning-lint: an open gated child with no `gate:` justification line.
    // Checkpoint and escalation gates are structural, not linted; the match
    // is word-bounded, so "investigate:" prose cannot pass as one.
    const gateLint: string[] = [];
    for (const t of tasks) {
      let gated = typeof t.requires === "string" && t.requires !== "";
      if (
        !gated &&
        isAwaitingHuman(t) &&
        t.awaiting !== "checkpoint" &&
        t.awaiting !== "escalation"
      ) {
        gated = true;
      }
      if (!gated) continue;
      const text = `${t.description ?? ""}\n${t.notes ?? ""}`.toLowerCase();
      if (/\bgate:/.test(text)) continue;
      gateLint.push(t.id);
    }

    const graphWaves: GraphWave[] = waves.map((w) => ({
      wave: w.level,
      parallel: w.tasks.length,
      ready: w.level === 1,
      tasks: w.tasks.map((t) => this.#graphTask(t, openBlockers, dependents, now)),
    }));

    return {
      epic: { id: epic.id, title: epic.title },
      needs_planning: false,
      missing_process_ticks: missingProcess,
      unjustified_gates: gateLint,
      stats: {
        total_tasks: tasks.length,
        wave_count: waves.length,
        max_parallel: maxParallel,
        ready_for_agent: readyForAgent,
        awaiting_human: awaitingHuman,
        deferred: deferred,
      },
      dispatch: {
        max_parallel: width.value,
        source: width.source === "" ? undefined : width.source,
        in_flight: inFlightIDs.length,
        in_flight_ids: inFlightIDs,
        free,
        now: nowIDs,
      },
      waves: graphWaves,
      critical_path: waves.length,
    };
  }

  #graphTask(
    t: Tick,
    openBlockers: Map<string, string[]>,
    dependents: Map<string, string[]>,
    now: Date,
  ): GraphTask {
    const task: GraphTask = {
      id: t.id,
      title: t.title,
      priority: t.priority,
      status: t.status,
      agent_ready:
        !isDeferred(t, now) &&
        !isAwaitingHuman(t) &&
        (openBlockers.get(t.id)?.length ?? 0) === 0 &&
        t.status !== "closed",
    };
    if ((t.description ?? "") !== "") task.description = t.description;
    if ((t.acceptance_criteria ?? "") !== "") task.acceptance_criteria = t.acceptance_criteria;
    if ((t.type ?? "") !== "") task.type = t.type;
    if ((t.labels?.length ?? 0) > 0) task.labels = t.labels;
    if ((t.role ?? "") !== "") task.role = t.role;
    const blocked = openBlockers.get(t.id);
    if (blocked !== undefined && blocked.length > 0) task.blocked_by = blocked;
    const blocks = dependents.get(t.id);
    if (blocks !== undefined && blocks.length > 0) task.blocks = blocks;
    if ((t.awaiting ?? "") !== "") task.awaiting = t.awaiting;
    if (isDeferred(t, now)) task.deferred_until = (t.defer_until ?? "").slice(0, 10);
    return task;
  }

  // ------------------------------------------------------ controlled writes ---

  /**
   * `tk update <id> --status in_progress --owner <owner> --json`.
   *
   * There is no separate claim verb — a claim IS this update, and it is where
   * the wave-width gate runs: a claim past `[orchestration].max_parallel`
   * under the tick's parent epic is refused (`wave_full`, a
   * retry-when-a-slot-frees). A re-claim of an already in_progress tick is
   * idempotent and keeps its `started_at`.
   */
  async claim(id: string, owner: string): Promise<TrackerWrite> {
    const all = await this.#all();
    const found = all.find((t) => t.id === id);
    if (found === undefined)
      return { state: "refused", reason: "not_found", detail: `no tick ${id}` };
    // reconciler-decision:D28:begin:claim — this claim reads the tick's
    // existence and the wave width, never its blockers; the local window
    // holds a tick behind its blockers before the claim is ever made
    // (decisions/reconciler-parity.json, D26 and D28).
    const width = await this.#width();
    if (typeof found.parent === "string" && found.parent !== "" && width.value > 0) {
      const inFlight = all.filter(
        (t) =>
          t.parent === found.parent &&
          t.id !== id &&
          t.type !== "epic" &&
          t.status === "in_progress",
      );
      if (inFlight.length >= width.value) {
        return {
          state: "refused",
          reason: "wave_full",
          detail:
            `wave width ${width.value} is full: ${inFlight.length} implementer(s) already in flight under ` +
            `${found.parent} (${inFlight
              .map((t) => t.id)
              .sort()
              .join(", ")}); the width is ` +
            `${width.source}[orchestration].max_parallel`,
          tick: found,
        };
      }
    }
    // reconciler-decision:D28:end:claim
    return this.#commit(id, (tick) => {
      // Idempotent re-claim: an already in_progress tick keeps its started_at.
      if (tick.status !== "in_progress") {
        tick.status = "in_progress";
        tick.started_at = rfc3339(this.#now());
      }
      delete tick.closed_at;
      delete tick.closed_reason;
      tick.owner = owner;
      tick.updated_at = rfc3339(this.#now());
    });
  }

  /**
   * `tk update <id> --notes <text> --json` shape: set only the flags passed; a
   * flag given an empty value clears the field.
   */
  async update(id: string, fields: { notes?: string }): Promise<TrackerWrite> {
    if (Object.hasOwn(fields, "notes")) {
      return this.#commit(id, (tick) => {
        if (fields.notes === "") delete tick.notes;
        else tick.notes = fields.notes;
        tick.updated_at = rfc3339(this.#now());
      });
    }
    const found = await this.#find(id);
    return found === null
      ? { state: "refused", reason: "not_found", detail: `no tick ${id}` }
      : { state: "written", tick: found.tick };
  }

  /**
   * `tk note <id> <text> --json`: append one timestamped line.
   *
   * `--from human` is a durable provenance boundary: it marks the line `[human]`,
   * and an ORCHESTRATOR must never pass it for its own notes — the same rule
   * the manifest's description pins on this command.
   */
  async note(
    id: string,
    text: string,
    options: { from?: "agent" | "human" } = {},
  ): Promise<TrackerWrite> {
    const trimmed = text.trim();
    if (trimmed === "") {
      return { state: "refused", reason: "gate", detail: "note text is required" };
    }
    const from = options.from ?? "agent";
    const timestamp = noteTimestamp(this.#now());
    const line =
      from === "human" ? `${timestamp} - [human] ${trimmed}` : `${timestamp} - ${trimmed}`;
    return this.#commit(id, (tick) => {
      tick.notes = appendNote(tick.notes, line);
      tick.updated_at = rfc3339(this.#now());
    });
  }

  /**
   * `tk close <id> --json`. A tick with an unmet gate is REFUSED rather than
   * closed: a `--requires` tick is routed to `awaiting: <gate>` with the note
   * tk writes, and an epic with open children is refused (the published close
   * has no `--force`).
   */
  async close(id: string, options: { reason?: string } = {}): Promise<TrackerWrite> {
    const all = await this.#all();
    const found = all.find((t) => t.id === id);
    if (found === undefined)
      return { state: "refused", reason: "not_found", detail: `no tick ${id}` };

    if (found.type === "epic") {
      const openChildren = all.filter((t) => t.parent === id && t.status !== "closed");
      if (openChildren.length > 0) {
        return {
          state: "refused",
          reason: "gate",
          detail:
            `epic ${id} has ${openChildren.length} open children ` +
            `(${openChildren
              .map((t) => t.id)
              .sort()
              .join(", ")})`,
          tick: found,
        };
      }
    }

    if (typeof found.requires === "string" && found.requires !== "") {
      // HandleClose's routing: the tick moves to awaiting its gate, with the
      // note explaining it — as a timestamped line, exactly the line tk's
      // own routing writes — and the close is refused.
      const stamp = noteTimestamp(this.#now());
      const routed = await this.#commit(id, (tick) => {
        tick.awaiting = found.requires;
        tick.notes = appendNote(tick.notes, `${stamp} - Work complete, awaiting ${found.requires}`);
        tick.updated_at = rfc3339(this.#now());
      });
      if (routed.state === "written") {
        return {
          state: "refused",
          reason: "gate",
          detail: `tick ${id} requires ${found.requires} before closing; routed to awaiting`,
          tick: routed.tick,
        };
      }
      return routed;
    }

    return this.#commit(id, (tick) => {
      tick.status = "closed";
      tick.closed_at = rfc3339(this.#now());
      tick.closed_reason = (options.reason ?? "").trim();
      if (tick.closed_reason === "") delete tick.closed_reason;
      delete tick.started_at;
      tick.updated_at = rfc3339(this.#now());
    });
  }

  /** `tk reopen <id> --json`: back to open, closed_at and closed_reason cleared. */
  async reopen(id: string): Promise<TrackerWrite> {
    return this.#commit(id, (tick) => {
      tick.status = "open";
      delete tick.closed_at;
      delete tick.closed_reason;
      delete tick.started_at;
      tick.updated_at = rfc3339(this.#now());
    });
  }

  /**
   * Read-modify-write one record under the contents API's own
   * compare-and-swap: the ref moving between the read and the write is a
   * refusal with nothing committed, retried on a fresh read — so a write
   * here cannot land on a stale read of the tracker, the same guarantee
   * `internal/reconcile`'s durableTracker publishes for.
   */
  async #commit(id: string, mutate: (tick: Tick) => void): Promise<TrackerWrite> {
    let lastDetail = "no attempt was made";
    for (let attempt = 1; attempt <= MAX_WRITE_ATTEMPTS; attempt += 1) {
      const found = await this.#find(id);
      if (found === null) {
        return {
          state: "refused",
          reason: "not_found",
          detail: `no tick ${id} on ${this.project} at ${this.ref}`,
        };
      }
      const tick: Tick = structuredClone(found.tick);
      mutate(tick);
      const content = encodeTick(tick);
      if (content === found.file.content) {
        // The write is already what the tracker holds — an idempotent repeat
        // of the same mutation. The answer is the record the ref holds.
        return { state: "written", tick };
      }
      const result = await this.store.update(`${TICK_RECORD_DIR}/${id}.json`, found.file.sha, {
        content,
        message: `tick ${id}: tracker update by the run reconciler`,
      });
      if (result.state === "written") return { state: "written", tick };
      if (result.state === "conflict") {
        lastDetail = result.detail;
        continue;
      }
      if (result.state === "missing" || result.state === "exists") {
        // A path this ref does not hold, or a ref disagreement this writer
        // cannot retry into. Report rather than guess.
        return { state: "refused", reason: "not_found", detail: result.detail };
      }
    }
    return {
      state: "refused",
      reason: "gate",
      detail: `${MAX_WRITE_ATTEMPTS} attempts to write tick ${id} all hit a moving ${this.ref}; last: ${lastDetail}`,
    };
  }
}

/** The client this deployment uses: a test's fake store, or the GitHub contents API. */
export function trackerClient(
  env: Env,
  project: string,
  ref: string,
  options: TrackerClientOptions = {},
): TrackerClient {
  return new TrackerClient(contentsStore(env, project, ref), project, ref, options);
}
